version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
