[phases.setup]
nixPkgs = ["python313", "python313Packages.pip", "python313Packages.virtualenv"]

[phases.install]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "/opt/venv/bin/python -m bot.main"
