[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "python312Packages.virtualenv"]

[phases.install]
cmds = ["python -m venv /opt/venv", "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python -m bot.main"
